spring:
  application:
    name: cache-service
  profiles:
    default:

cache:
  redis:
    host: redis-prod-host.example.com
    port: 6379
    password: yourStrongRedisPasswordHere
    database: 0
    command-timeout: 2s
    time-to-live: 10m
    use-ssl: false
    pool-max-total: 16
    pool-max-idle: 16
    pool-min-idle: 4
    pool-max-wait: 1s
    auto-reconnect: true
    enabled: true
    sentinel:
      master: mymaster
      nodes:
        - sentinel1:26379
        - sentinel2:26379
        - sentinel3:26379
    cluster:
      nodes:
        - redis-node1:6379
        - redis-node2:6379
        - redis-node3:6379
